### ISSUE TITLE
LinkedList removed isCached variable

### ISSUE THREAD

**Issue by sgraber** [ivanseidel/Gaussian#1]
4 days ago, LinkedList removed the 'isCached' variable, which is now causing a compilation error with Gaussian:  https://github.com/ivanseidel/LinkedList/commit/e3526a8b58377d6523a1cebc1a009d1df66ebc00

Thought I'd make you aware!  :)

**Comment by ivanseidel** [comment]
Fixed! Thanks for the warning...
