### ISSUE TITLE
errors when including GaussianAverage

### ISSUE THREAD

**Issue by waspinator** [ivanseidel/Gaussian#3]
Can't compile when trying to include GaussianAverage.h

```
#include <LinkedList.h>
#include <GaussianAverage.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:29:1: error: expected class-name before '{' token
 {
 ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:32:13: error: 'Gaussian' was not declared in this scope
  LinkedList<Gaussian> _gaussians;
             ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:32:21: error: template argument 1 is invalid
  LinkedList<Gaussian> *gaussians;
                     ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:41:2: error: 'Gaussian' does not name a type
  Gaussian avg;
  ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:58:19: error: 'Gaussian' has not been declared
  virtual void add(Gaussian _gaus){
                   ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:71:26: error: 'Gaussian' has not been declared
  virtual void operator+=(Gaussian _gaus){
                          ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:85:10: error: 'Gaussian' does not name a type
  virtual Gaussian process(){
          ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h: In constructor 'GaussianAverage::GaussianAverage(int)':
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:48:31: error: class 'GaussianAverage' does not have any field named 'Gaussian'
  GaussianAverage(int _n = 4): Gaussian(){
                               ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:49:30: error: 'Gaussian' was not declared in this scope
   gaussians = new LinkedList<Gaussian>();  
                              ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:49:38: error: template argument 1 is invalid
   gaussians = new LinkedList<Gaussian>();  
                                      ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h: In member function 'virtual void GaussianAverage::add(int)':
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:62:20: error: request for member 'size' in '_((GaussianAverage_)this)->GaussianAverage::gaussians', which is of non-class type 'int'
   while(gaussians->size() >= n)
                    ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:63:15: error: request for member 'shift' in '_((GaussianAverage_)this)->GaussianAverage::gaussians', which is of non-class type 'int'
    gaussians->shift();
               ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:65:14: error: request for member 'add' in '_((GaussianAverage*)this)->GaussianAverage::gaussians', which is of non-class type 'int'
   gaussians->add(_gaus);
              ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h: In member function 'virtual void GaussianAverage::operator+=(double)':
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:79:21: error: 'Gaussian' was not declared in this scope
   add(Gaussian(_mean));
                     ^
Error compiling.

**Comment by ivanseidel** [comment]
Hi,

Because GaussianAverage depends on Gaussian, you must include Gaussian.h
before GaussianAverage, even if you are not directly using Gaussian.

Hope it helps

**Comment by waspinator** [comment]
Hmm, still get an error.

```
#include <Gaussian.h>
#include <LinkedList.h>
#include <GaussianAverage.h>

void setup() {
// put your setup code here, to run once:

}

void loop() {
// put your main code here, to run repeatedly:

}
```

In file included from sketch_oct14b.ino:3:0:
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h: In member function 'virtual Gaussian GaussianAverage::process()':
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:90:32: error: no matching function for call to 'LinkedList<Gaussian>::get(int, bool)'
    avg = gaussians->get(0, true);
                                ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:90:32: note: candidate is:
In file included from sketch_oct14b.ino:2:0:
C:\Users\waspinator\Documents\Arduino\libraries\LinkedList/LinkedList.h:311:3: note: T LinkedList<T>::get(int) [with T = Gaussian]
 T LinkedList<T>::get(int index){
   ^
C:\Users\waspinator\Documents\Arduino\libraries\LinkedList/LinkedList.h:311:3: note:   candidate expects 1 argument, 2 provided
In file included from sketch_oct14b.ino:3:0:
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:92:42: error: no matching function for call to 'LinkedList<Gaussian>::get(int&, bool)'
     Gaussian tmp = gaussians->get(i, true);
                                          ^
C:\Users\waspinator\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:92:42: note: candidate is:
In file included from sketch_oct14b.ino:2:0:
C:\Users\waspinator\Documents\Arduino\libraries\LinkedList/LinkedList.h:311:3: note: T LinkedList<T>::get(int) [with T = Gaussian]
 T LinkedList<T>::get(int index){
   ^
C:\Users\waspinator\Documents\Arduino\libraries\LinkedList/LinkedList.h:311:3: note:   candidate expects 1 argument, 2 provided
Error compiling.

**Comment by ivanseidel** [comment]
Just fixed it...
LinkedList changed the fingerprint of a method, and GaussianAverage depended on that. Try downloading it again and checking

**Comment by ivanseidel** [comment]
Will mark as solved..

**Comment by addicted2maker** [comment]
I have the same problems, unfortunatelly.

```
#include <Gaussian.h>
#include <LinkedList.h>
#include <GaussianAverage.h>

void setup() {
// put your setup code here, to run once:

}

void loop() {
// put your main code here, to run repeatedly:

}
```

gives this:

> In file included from F:\arduino\testgaussian\testgaussian\testgaussian.ino:2:0:
>C:\Users\Levin\Documents\Arduino\libraries\LinkedList/LinkedList.h: In instantiation of 'ListNode<T>* LinkedList<T>::getNode(int) [with T = Gaussian]':
>C:\Users\Levin\Documents\Arduino\libraries\LinkedList/LinkedList.h:314:28:   required from 'T LinkedList<T>::get(int) [with T = Gaussian]'
>C:\Users\Levin\Documents\Arduino\libraries\Gaussian/GaussianAverage.h:90:26:   required from here
>C:\Users\Levin\Documents\Arduino\libraries\LinkedList/LinkedList.h:160:9: error: cannot convert 'bool' to 'ListNode<Gaussian>*' in return
>  return false;
>exit status 
> 1
